title: "鑰佸彾鐨勫崥瀹?
description: "璁板綍涓庢€濊€?
remote_theme: just-the-docs/just-the-docs@v0.10.1
url: "https://aaryn-hs.github.io"

# 鎼滅储
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  rel_url: true
  button: false

# 棰滆壊涓婚
color_scheme: light

# 瀵艰埅
aux_links:
  "GitHub":
    - "https://github.com/Aaryn-hs"
aux_links_new_tab: true

# 鍚敤鐩綍
nav_sort: case_sensitive
heading_anchors: true

# 椤佃剼
footer_content: "Copyright &copy; 2026 鑰佸彾. Distributed by an <a href=\"https://github.com/Aaryn-hs/aaryn-hs.github.io/tree/main\">open source project.</a>"

# 鎻掍欢
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# GitHub Metadata (optional, for better repo integration)
repository: Aaryn-hs/aaryn-hs.github.io
